//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by BookAppoint.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDS_TOOLBAR_STANDARD            124
#define IDS_TOOLBAR_CUSTOMIZE           125
#define ID_VIEW_CUSTOMIZE               126
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_BookAppointTYPE             130
#define ID_WINDOW_MANAGER               131
#define IDR_THEME_MENU                  200
#define ID_SET_STYLE                    201
#define ID_VIEW_APPLOOK_WIN_2000        205
#define ID_VIEW_APPLOOK_OFF_XP          206
#define ID_VIEW_APPLOOK_WIN_XP          207
#define ID_VIEW_APPLOOK_OFF_2003        208
#define ID_VIEW_APPLOOK_VS_2005         209
#define ID_VIEW_APPLOOK_VS_2008         210
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   218
#define ID_VIEW_APPLOOK_WINDOWS_7       219
#define IDS_EDIT_MENU                   306
#define IDD_BOOKAPPOINT_LOGIN           310
#define IDD_BOOKAPPOINT_REGISTRATION    315
#define IDD_BOOKAPPOINT_MODIFY_UPDATE   317
#define IDD_BOOKAPPOINT_MODIFY_UPDATE_ONCLICKEDEDITBUTTON 319
#define IDR_MAIN_MENU                   321
#define IDD_BOOKAPPOINT                 322
#define IDD_BOOKAPPOINTMENT_DLG         324
#define IDLOGIN                         1000
#define IDC_USERNAME                    1001
#define IDC_PASSWORD                    1002
#define IDCONFIRM                       1003
#define IDC_EDIT_PATIENT_NAME           1004
#define IDC_DATETIMEPICKER_DOB          1005
#define IDC_COMBO_GENDER                1007
#define IDC_COMBO_COUNTRY_CODE          1008
#define IDC_EDIT_CONTACT_NUMBER         1009
#define IDC_EDIT_ADDRESS                1010
#define IDC_LIST_MODIFY_SEARCH_OUTPUT   1012
#define IDC_RADIO_SEARCH_MODIFY_DOB     1013
#define IDC_RADIO_SEARCH_MODIFY_CONTACT_NUMBER 1014
#define IDC_RADIO_SEARCH_MODIFY_NAME    1015
#define IDC_RADIO_SEARCH_MODIFY_ALL     1016
#define IDC_DATETIMEPICKER_SEARCH_MODIFY_DOB 1017
#define IDC_COMBO_SEARCH_MODIFY_COUNTRY_CODE 1018
#define IDC_EDIT_SEARCH_MODIFY_CONTACT_NUMBER 1019
#define IDC_EDIT_SEARCH_MODIFY_PATIENT_NAME 1020
#define IDC_BUTTON_SEARCH_MODIFY_RESET  1021
#define IDC_BUTTON_SEARCH_MODIFY_SEARCH 1022
#define ID_BUTTON_SEARCH_MODIFY_EDIT    1024
#define IDC_APPOINTMENT_DATE            1025
#define IDC_APPOINTMENT_START_TIME      1026
#define IDC_APPOINTMENT_END_TIME        1027
#define IDC_COMBO_SELECT_DEPARTMENT     1028
#define IDC_EDIT_DOCTOR_ID              1029
#define IDC_BUTTON_LIST_DOCTORS         1030
#define IDC_EDIT_PATIENT_ID             1031
#define IDC_EDIT_SUBJECT_LINE           1032
#define IDC_LIST_APPOINTMENTBOOKING     1033
#define IDC_BUTTON_VIEW_APPOINTMENT_DETAILS 1034
#define IDC_LIST1                       1035
#define IDC_ADD_DOCTOR_ID               1036
#define IDC_MONTHCALENDAR_VIEW_APPOINTMENTS 1037
#define IDC_APPOINTMENT_LOCATION        1038
#define IDC_LIST_VIEW_APPOINTMENTS      1039
#define IDC_RADIO_VIEW_APPOINTMENTS_DOCTOR_ID 1040
#define IDC_RADIO_VIEW_APPOINTMENTS_PATIENT_ID 1041
#define IDC_RADIO_VIEW_APPOINTMENTS_DATE_INTERVAL 1042
#define IDC_EDIT_VIEW_APPOINTMENTS_DOCTOR_ID 1043
#define IDC_EDIT_VIEW_APPOINTMENTS_PATIENT_ID 1044
#define IDC_DATETIMEPICKER_VIEW_APPOINTMENTS_START_DATE 1045
#define IDC_DATETIMEPICKER_VIEW_APPOINTMENTS_END_DATE 1046
#define IDSEARCH                        1047
#define IDC_CANCEL_APPOINTMENT          1048
#define IDC_BUTTON_MARK_AS_SEEN         1049
#define IDC_BUTTON_MARK_AS_NO_SHOW      1050
#define IDC_DATETIMEPICKER_VIEW_APPOINTMENTS_START_TIME 1051
#define IDC_DATETIMEPICKER_VIEW_APPOINTMENTS_END_TIME 1052
#define IDC_RADIO_VIEW_APPOINTMENTS_TIME_INTERVAL 1053
#define IDC_COMBO_LIST_DEPARTMENT       1054
#define IDC_BUTTON_ADD_DOCTOR           1057
#define IDC_BUTTON1                     1058
#define IDC_BUTTON_CLEAR_FILTER         1058
#define IDC_RADIO_VIEW_APPOINTMENTS_All 1059
#define ID_REGISTRATION                 32771
#define ID_MODIFY                       32772
#define ID_MODIFY_UPDATE                32773
#define ID_BOOKAPPOINTMENT              32774
#define ID_REGISTRATION32775            32775
#define ID_MODIFY32776                  32776

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        326
#define _APS_NEXT_COMMAND_VALUE         32777
#define _APS_NEXT_CONTROL_VALUE         1060
#define _APS_NEXT_SYMED_VALUE           310
#endif
#endif
